// Placeholder content shown when the Google Sheet isn't configured yet (no env vars) or is
// reachable but empty. Lets `npm run dev` render a real-looking menu before the spreadsheet
// exists. Swapped out automatically the moment the sheet returns real rows — see getMenuData().
//
// "coconut" is deliberately marked out of stock below, so Frost Resistance Potion (and Daisy
// Sunshine, which shares the ingredient) render crossed-out on first run — a live demo of the
// inventory cascade, not a mistake.
import type { Ingredient, Recipe, Message, Screen } from "./drinksData";

export const sampleIngredients: Ingredient[] = [
    // Spirits. `icon` is set explicitly here rather than left to IngredientGlyph's
    // keyword-fallback guess (see components/icons.tsx) — bourbon, kahlua, and prosecco don't
    // match any of that fallback's keywords, so they'd otherwise silently render with no glyph.
    { id: "vodka", name: "Vodka", kind: "spirit", icon: "🍾", color: "#cbd5e1", inStock: true },
    { id: "gin", name: "Gin", kind: "spirit", icon: "🌿", color: "#4ade80", inStock: true },
    { id: "tequila", name: "Tequila", kind: "spirit", icon: "🌵", color: "#eab308", inStock: true },
    { id: "white-rum", name: "White Rum", kind: "spirit", icon: "🌴", color: "#38bdf8", inStock: true },
    { id: "dark-rum", name: "Dark Rum", kind: "spirit", icon: "🌴", color: "#4a2c0f", inStock: true },
    { id: "bourbon", name: "Bourbon", kind: "spirit", icon: "🥃", color: "#b5651d", inStock: true },
    { id: "red-wine", name: "Red Wine", kind: "spirit", icon: "🍷", color: "#7f1d1d", inStock: true },
    { id: "kahlua", name: "Kahlúa", kind: "spirit", icon: "☕", color: "#3b1f0f", inStock: true },
    // Prosecco doubles as a Basics beverage and a cocktail base — same single ingredient
    // either way, so it renders in the spirit/glyph row for both (kind is a property of the
    // ingredient, not the recipe), unlike Lager/IPA/Cider/Soda below which are kind "other"
    // and render in the flavor row instead.
    { id: "prosecco", name: "Prosecco", kind: "spirit", icon: "🥂", color: "#eab308", inStock: true },

    // Elixir flavor ingredients
    { id: "pomegranate", name: "Pomegranate", kind: "other", icon: undefined, color: "#dc2626", inStock: true },
    { id: "blue-raspberry", name: "Blue Raspberry", kind: "other", icon: undefined, color: "#2563eb", inStock: true },
    { id: "kiwi", name: "Kiwi", kind: "other", icon: undefined, color: "#16a34a", inStock: true },
    { id: "green-apple", name: "Green Apple", kind: "other", icon: undefined, color: "#4ade80", inStock: true },
    { id: "grape", name: "Grape", kind: "other", icon: undefined, color: "#9333ea", inStock: true },
    { id: "blackberry", name: "Blackberry", kind: "other", icon: undefined, color: "#581c87", inStock: true },
    { id: "lemon", name: "Lemon", kind: "other", icon: undefined, color: "#ca8a04", inStock: true },
    { id: "yuzu", name: "Yuzu", kind: "other", icon: undefined, color: "#facc15", inStock: true },
    { id: "mango", name: "Mango", kind: "other", icon: undefined, color: "#ea580c", inStock: true },
    { id: "chili", name: "Chili", kind: "other", icon: undefined, color: "#dc2626", inStock: true },
    { id: "mint", name: "Mint", kind: "other", icon: undefined, color: "#0891b2", inStock: true },
    { id: "coconut", name: "Coconut", kind: "other", icon: undefined, color: "#f8fafc", inStock: false },
    { id: "licorice", name: "Licorice", kind: "other", icon: undefined, color: "#2b1640", inStock: true },
    { id: "raspberry", name: "Raspberry", kind: "other", icon: undefined, color: "#be123c", inStock: true },
    { id: "strawberry", name: "Strawberry", kind: "other", icon: undefined, color: "#db2777", inStock: true },
    { id: "cotton-candy", name: "Cotton Candy", kind: "other", icon: undefined, color: "#f9a8d4", inStock: true },
    { id: "pear", name: "Pear", kind: "other", icon: undefined, color: "#65a30d", inStock: true },

    // Drinks-screen flavor ingredients ("Choose your character")
    { id: "coffee", name: "Coffee", kind: "other", icon: undefined, color: "#78350f", inStock: true },
    { id: "vanilla", name: "Vanilla", kind: "other", icon: undefined, color: "#fef3c7", inStock: true },
    { id: "lime", name: "Lime", kind: "other", icon: undefined, color: "#65a30d", inStock: true },
    { id: "peach", name: "Peach", kind: "other", icon: undefined, color: "#fda4af", inStock: true },
    { id: "cherry", name: "Cherry", kind: "other", icon: undefined, color: "#b91c1c", inStock: true },
    { id: "cinnamon", name: "Cinnamon", kind: "other", icon: undefined, color: "#a3672b", inStock: true },
    { id: "honeydew", name: "Honeydew Melon", kind: "other", icon: undefined, color: "#bef264", inStock: true },
    { id: "marshmallow", name: "Marshmallow", kind: "other", icon: undefined, color: "#fbcfe8", inStock: true },
    { id: "passion-fruit", name: "Passion Fruit", kind: "other", icon: undefined, color: "#f59e0b", inStock: true },
    { id: "pineapple", name: "Pineapple", kind: "other", icon: undefined, color: "#fde047", inStock: true },
    { id: "earl-grey", name: "Earl Grey", kind: "other", icon: undefined, color: "#6b4226", inStock: true },
    { id: "honey", name: "Honey", kind: "other", icon: undefined, color: "#d97706", inStock: true },
    { id: "chocolate", name: "Chocolate", kind: "other", icon: undefined, color: "#45250f", inStock: true },
    { id: "hazelnut", name: "Hazelnut", kind: "other", icon: undefined, color: "#8a5a34", inStock: true },
    { id: "elderflower", name: "Elderflower", kind: "other", icon: undefined, color: "#e9d8fd", inStock: true },
    { id: "apple", name: "Apple", kind: "other", icon: undefined, color: "#dc2626", inStock: true },
    { id: "banana", name: "Banana", kind: "other", icon: undefined, color: "#fef08a", inStock: true },
    { id: "toffee", name: "Toffee", kind: "other", icon: undefined, color: "#92400e", inStock: true },
    { id: "ginger", name: "Ginger", kind: "other", icon: undefined, color: "#eab308", inStock: true },

    // Basics screen — each is its own "ingredient" (a whole beverage, not a recipe). These render
    // in the flavor row (kind "other"), which — unlike the spirit row — didn't render
    // IngredientGlyph at all until PotionCard.tsx was updated to, so these glyphs used to be
    // unreachable regardless of icon/fallback.
    { id: "lager", name: "Lager", kind: "other", icon: "🍺", color: "#d97706", inStock: true },
    { id: "ipa", name: "IPA", kind: "other", icon: "🍺", color: "#ca8a04", inStock: true },
    { id: "cider", name: "Cider", kind: "other", icon: "🍏", color: "#65a30d", inStock: true },
    { id: "soda", name: "Soda", kind: "other", icon: "🥤", color: "#0ea5e9", inStock: true },
];

// `price` is optional per recipe and overrides the screen's shared price (see sampleScreens)
// when a particular drink costs something different, e.g. Poison and Love Potion below.
// `emblem` is embossed into the potion icon (see PotionIcon) — matches reference/elixirs.jpg's
// per-potion glyphs (heart, star, skull, etc.) for the Elixirs screen; the Drinks screen's
// glyphs come from the character each cocktail is themed after.
export const sampleRecipes: Recipe[] = [
    {
        order: 1,
        category: "elixirs",
        name: "Health",
        emblem: "❤️",
        ingredientIds: ["vodka", "pomegranate"],
        active: true,
        price: 139,
    },
    {
        order: 2,
        category: "elixirs",
        name: "Mana",
        emblem: "⭐",
        ingredientIds: ["vodka", "blue-raspberry"],
        active: true,
        price: 139,
    },
    {
        order: 3,
        category: "elixirs",
        name: "Stamina",
        emblem: "🍃",
        ingredientIds: ["gin", "kiwi", "green-apple"],
        active: true,
        price: 139,
    },
    {
        order: 4,
        category: "elixirs",
        name: "Poison",
        emblem: "💀",
        ingredientIds: ["vodka", "grape", "blackberry"],
        active: true,
        price: 119,
    },
    {
        order: 5,
        category: "elixirs",
        name: "Speed",
        emblem: "⚡",
        ingredientIds: ["gin", "lemon", "yuzu"],
        active: true,
        price: 139,
    },
    {
        order: 6,
        category: "elixirs",
        name: "Fire Resistance",
        emblem: "🔥",
        ingredientIds: ["tequila", "mango", "chili"],
        active: true,
        price: 139,
    },
    {
        order: 7,
        category: "elixirs",
        name: "Frost Resistance",
        emblem: "❄️",
        ingredientIds: ["white-rum", "mint", "coconut"],
        active: true,
        price: 139,
    },
    {
        order: 8,
        category: "elixirs",
        name: "Shadow",
        emblem: "🌙",
        ingredientIds: ["vodka", "licorice", "raspberry"],
        active: true,
        price: 139,
    },
    {
        order: 9,
        category: "elixirs",
        name: "Love",
        emblem: "💗",
        ingredientIds: ["vodka", "strawberry", "cotton-candy"],
        active: true,
        price: 149,
    },
    {
        order: 10,
        category: "elixirs",
        name: "Luck",
        emblem: "🍀",
        ingredientIds: ["gin", "pear", "grape"],
        active: true,
        price: 139,
    },
    {
        order: 1,
        category: "drinks",
        name: "Peach Cocktail",
        emblem: "👑",
        ingredientIds: ["peach", "vanilla", "vodka", "prosecco"],
        active: true,
        price: 149,
    },
    {
        order: 2,
        category: "drinks",
        name: "Daisy Sunshine",
        emblem: "🌼",
        ingredientIds: ["mango", "coconut", "vanilla", "lime", "white-rum"],
        active: true,
        price: 149,
    },
    {
        order: 3,
        category: "drinks",
        name: "Mario Berry Blast",
        emblem: "🍄",
        ingredientIds: ["strawberry", "cherry", "vodka"],
        active: true,
        price: 139,
    },
    {
        order: 4,
        category: "drinks",
        name: "Luigi Lime",
        emblem: "💚",
        ingredientIds: ["lime", "green-apple", "mint", "gin"],
        active: true,
        price: 139,
    },
    {
        order: 5,
        category: "drinks",
        name: "Bowser Inferno",
        emblem: "🐢",
        ingredientIds: ["cherry", "cinnamon", "chili", "bourbon"],
        active: true,
        price: 159,
    },
    {
        order: 6,
        category: "drinks",
        name: "Yoshi Melon",
        emblem: "🥚",
        ingredientIds: ["honeydew", "kiwi", "vodka"],
        active: true,
        price: 139,
    },
    {
        order: 7,
        category: "drinks",
        name: "Kirby Pink Puff",
        emblem: "⭐",
        ingredientIds: ["strawberry", "marshmallow", "vodka"],
        active: true,
        price: 139,
    },
    {
        order: 8,
        category: "drinks",
        name: "Mega Man Blue Burst",
        emblem: "🤖",
        ingredientIds: ["blue-raspberry", "lemon", "vodka"],
        active: true,
        price: 139,
    },
    {
        order: 9,
        category: "drinks",
        name: "Pikachu Thunder",
        emblem: "⚡",
        ingredientIds: ["passion-fruit", "lemon", "pineapple", "white-rum"],
        active: true,
        price: 149,
    },
    {
        order: 10,
        category: "drinks",
        name: "Cuphead Earl Grey",
        emblem: "☕",
        ingredientIds: ["earl-grey", "honey", "vanilla", "bourbon"],
        active: true,
        price: 159,
    },
    {
        order: 11,
        category: "drinks",
        name: "Mugman Cocoa",
        emblem: "🍫",
        ingredientIds: ["chocolate", "hazelnut", "vanilla", "kahlua", "vodka"],
        active: true,
        price: 159,
    },
    {
        order: 12,
        category: "drinks",
        name: "Zelda's Royal Bloom",
        emblem: "🗡",
        ingredientIds: ["pear", "grape", "elderflower", "gin"],
        active: true,
        price: 169,
    },
    {
        order: 13,
        category: "drinks",
        name: "Crash Wumpa",
        emblem: "🍎",
        ingredientIds: ["apple", "mango", "passion-fruit", "white-rum"],
        active: true,
        price: 149,
    },
    {
        order: 14,
        category: "drinks",
        name: "Donkey Kong Banana Smash",
        emblem: "🦍",
        ingredientIds: ["banana", "toffee", "dark-rum"],
        active: true,
        price: 149,
    },
    {
        order: 15,
        category: "drinks",
        name: "Leon Kennedy – Rookie's Remedy",
        emblem: "🦁",
        ingredientIds: ["lemon", "green-apple", "ginger", "gin"],
        active: true,
        price: 159,
    },
    {
        order: 16,
        category: "drinks",
        name: "Lady Dimitrescu",
        emblem: "🧛",
        ingredientIds: ["cherry", "blackberry", "vanilla", "red-wine", "dark-rum"],
        active: true,
        price: 179,
    },
    {
        order: 17,
        category: "drinks",
        name: "Gordon Freeman",
        emblem: "👨‍🔬",
        ingredientIds: ["coffee", "chocolate", "hazelnut", "kahlua", "vodka"],
        active: true,
        price: 159,
    },
    {
        order: 1,
        category: "basics",
        name: "Lager",
        emblem: "🍺",
        ingredientIds: ["lager"],
        active: true,
        price: 79,
    },
    {
        order: 2,
        category: "basics",
        name: "IPA",
        emblem: "🍺",
        ingredientIds: ["ipa"],
        active: true,
        price: 89,
    },
    {
        order: 3,
        category: "basics",
        name: "Cider",
        emblem: "🍏",
        ingredientIds: ["cider"],
        active: true,
        price: 79,
    },
    {
        order: 4,
        category: "basics",
        name: "Prosecco",
        emblem: "🥂",
        ingredientIds: ["prosecco"],
        active: true,
        price: 99,
    },
    {
        order: 5,
        category: "basics",
        name: "Soda",
        emblem: "🥤",
        ingredientIds: ["soda"],
        active: true,
        price: 49,
    },
];

export const sampleMessages: Message[] = [
    {
        order: 1,
        text: "HAPPY HOUR: BEER, CIDER, WINE, SPARKLING & SODA UNTIL 23:00!",
        active: true,
        fromTime: undefined,
        toTime: "23:00",
    },
    {
        order: 2,
        text: "WELCOME TO SYNTAX ERROR!",
        active: true,
        fromTime: undefined,
        toTime: undefined,
    },
    {
        order: 3,
        text: "DON'T FORGET TO PARTICIPATE IN THE QUIZ WALK!",
        active: true,
        fromTime: undefined,
        toTime: "01:00",
    },
];

export const sampleScreens: Screen[] = [
    // {
    //     order: 1,
    //     key: "elixirs",
    //     title: "Elixirs",
    //     subtitle: "Choose your potion",
    //     durationSeconds: 14,
    //     active: true,
    //     template: "elixirs",
    // },
    {
        order: 2,
        key: "drinks",
        title: "Drinks",
        subtitle: "Choose your character",
        durationSeconds: 14,
        active: true,
        template: "drinks",
    },
    // {
    //     order: 3,
    //     key: "basics",
    //     title: "The Basics",
    //     subtitle: "Beer · Cider · Wine · Soda",
    //     durationSeconds: 14,
    //     active: true,
    //     template: "elixirs",
    // },
];
